name: Build and Release IPA

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          submodules: recursive  # Ensure submodules are checked out recursively

      - name: Install Homebrew dependencies
        run: |
          brew install ldid dpkg

      - name: Install Theos
        run: |
          # Clone Theos and ensure all submodules are updated
          git clone https://github.com/theos/theos.git ~/theos
          cd ~/theos
          # Force update of all submodules
          git submodule update --init --recursive --force
          # Set up environment variables
          export THEOS=~/theos
          export THEOS_MAKE_PATH=~/theos/makefiles
          echo "export THEOS=~/theos" >> $GITHUB_ENV
          echo "export THEOS_MAKE_PATH=~/theos/makefiles" >> $GITHUB_ENV

      - name: Force Submodule Update for Theos Makefiles
        run: |
          cd ~/theos
          git submodule foreach --recursive git fetch --all
          git submodule foreach --recursive git reset --hard
          git submodule update --init --recursive

      - name: Create Missing Makefiles (if needed)
        run: |
          mkdir -p ~/theos/makefiles
          echo -e "include \$(THEOS)/makefiles/common.mk\nCC = clang\nCFLAGS = -Wall" > ~/theos/makefiles/common.mk
          echo -e "TOOL_NAME = GeraniumRootHelper\nTOOLS = some_tool" > ~/theos/makefiles/tool.mk

      - name: Verify Theos Installation
        run: |
          echo "Checking Theos installation..."
          ls -la $THEOS
          ls -la $THEOS/makefiles
          ls -la $THEOS_MAKE_PATH
          cd ~/theos
          git submodule status

      - name: Run Build Script
        run: |
          chmod +x ./ipabuild.sh
          ./ipabuild.sh
        env:
          APPLICATION_NAME: Geranium
          CONFIGURATION: Debug
          THEOS: ${{ env.THEOS }}
          THEOS_MAKE_PATH: ${{ env.THEOS_MAKE_PATH }}

      - name: Rename IPA to Geranium.ipa
        run: |
          mv build/Geranium.tipa build/Geranium.ipa

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: latest
          release_name: Latest Build
          draft: false
          prerelease: false
          generate_release_notes: false
          overwrite: true

      - name: Upload IPA to Release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: build/Geranium.ipa
          asset_name: Geranium.ipa
          asset_content_type: application/zip
